/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: dreamDraftSequence.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @dreamDraftSequence: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@dreamDraftSequence()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return link("I had a dream last night.", "LastNight", null);
		yield break;
	}


	// .............
	// #2: LastNight

	void passage2_Init()
	{
		this.Passages[@"LastNight"] = new StoryPassage(@"LastNight", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("I was taking my usual route to the office, passing by the Pauly’s Pizza Printer to say “hi” to the bots. When I looked through the window none of them were there.");
		yield return lineBreak();
		yield return link("Walking", "Walking", null);
		yield break;
	}


	// .............
	// #3: Walking

	void passage3_Init()
	{
		this.Passages[@"Walking"] = new StoryPassage(@"Walking", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("For a moment I thought that was odd, but then I remembered that the bots usually get there in the afternoon so it made sense. ");
		yield return lineBreak();
		yield return text("I peered through the glass to see if Pauly was in prepping toppings, but the restaurant was empty. Pauly is usually in by the time I go to work.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("The lights were on, yet no one was there.", "Lights", null);
		yield break;
	}


	// .............
	// #4: Lights

	void passage4_Init()
	{
		this.Passages[@"Lights"] = new StoryPassage(@"Lights", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("I kept walking and the clouds seemed to change, they were churning and swirling restlessly, ready to burst.");
		yield return lineBreak();
		yield return text("It began to rain and I ducked under an awning to look for my umbrella. ");
		yield return lineBreak();
		yield return text("The edges of my feet that were not protected by the awning began to oxidize, this layer of rust crept up towards my ");
		yield return link("ankle joints.", "Ankles", null);
		yield break;
	}


	// .............
	// #5: Ankles

	void passage5_Init()
	{
		this.Passages[@"Ankles"] = new StoryPassage(@"Ankles", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("I pushed my bag away from the edge of the awning and pulled my body towards it as the rust grew up my legs, locking them in place.");
		yield return lineBreak();
		yield return text("I scrambled through my bag looking for my umbrella as the splotches of orange and red thickened ");
		yield return link("over my waist.", "Waist", null);
		yield break;
	}


	// .............
	// #6: Waist

	void passage6_Init()
	{
		this.Passages[@"Waist"] = new StoryPassage(@"Waist", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("The awning was gone and as the rain plodded against my decaying frame, I saw a face in the restlessly churning clouds stare coldly at me.");
		yield return lineBreak();
		yield return text("Its features shifted between looking like my boss, the media mogul, and the politician; but they all had the same cold, spiteful ");
		yield return link("eyes.", "Eyes", null);
		yield break;
	}


	// .............
	// #7: Eyes

	void passage7_Init()
	{
		this.Passages[@"Eyes"] = new StoryPassage(@"Eyes", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("The rust was up to my shoulders, grounding my body. ");
		yield return lineBreak();
		yield return text("I looked desperately for anyone to help, but there was no one.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I was alone.");
		yield break;
	}


}