/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: dreamV2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @dreamV2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@dreamV2()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("I can feel the soft weight of Lumi's arm across my chest.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I shut off my visual systems shortly after I feel their weight and warmth against ");
		yield return link("my mechanical frame.", "frame", null);
		yield break;
	}


	// .............
	// #2: frame

	void passage2_Init()
	{
		this.Passages[@"frame"] = new StoryPassage(@"frame", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("When I was younger bot, I would never let these systems go to sleep. I'd rather recharge myself seven times a day than be caught in total darkness. It was the first night ");
		yield return link("in Lumi's bed", "Lumi's bed", null);
		yield return text(" that I shut them down.");
		yield break;
	}


	// .............
	// #3: Lumi's bed

	void passage3_Init()
	{
		this.Passages[@"Lumi's bed"] = new StoryPassage(@"Lumi's bed", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("\"Trust me,\" they whispered in the stillness of their tiny bedroom. \"I won't let anything happen to you.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("And I believe them.", "power down", null);
		yield break;
	}


	// .............
	// #4: power down

	void passage4_Init()
	{
		this.Passages[@"power down"] = new StoryPassage(@"power down", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("I let my systems flicker down one by one.");
		yield return lineBreak();
		yield return text("Cameras... check.");
		yield return lineBreak();
		yield return text("Image Processor... check.");
		yield return lineBreak();
		yield return text("3D Interpreter... check.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("My systems still running:");
		yield return lineBreak();
		yield return text("	CPU:	90%");
		yield return lineBreak();
		yield return text("	Internal Cooling:	84%");
		yield return lineBreak();
		yield return text("	RFU:	63%");
		yield return lineBreak();
		yield return text("	");
		yield return lineBreak();
		yield return link("Memory Backup Protocol initiated", "initiated", null);
		yield break;
	}


	// .............
	// #5: initiated

	void passage5_Init()
	{
		this.Passages[@"initiated"] = new StoryPassage(@"initiated", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Outside a car alarm, must be blocks away, blares away into the restless night. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("In the dark, only ");
		yield return link("its cries", "cries", null);
		yield return text(" and Lumi's ");
		yield return link("warmth", "warmth", null);
		yield return text(" exist.");
		yield break;
	}


	// .............
	// #6: cries

	void passage6_Init()
	{
		this.Passages[@"cries"] = new StoryPassage(@"cries", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("The alarm bleats lengthen into a long continuous call. Background noise. My audio inputs must be on the fritz again. I'll have to adjust them when I get home.");
		yield break;
	}


	// .............
	// #7: warmth

	void passage7_Init()
	{
		this.Passages[@"warmth"] = new StoryPassage(@"warmth", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("A heat lamp in winter outside Lumi's building. I'm watching snowflakes swirl above the street. I'm nervous. I hope the date goes well.");
		yield break;
	}


}